kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: easyweb-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 190Gi
  volumeName: easyweb 
