kind: PersistentVolume
apiVersion: v1
metadata:
  name: v001
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/matias/kubedata/external/easyweb"
